import type { Product } from "./types";

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Mineral Water",
    price: "0.02",
    category: "Beverage",
    emoji: "💧",
    image: "/products/mineral-water.svg",
    company: "PT. Mineral Water Indonesia",
    tagline: "Pure Mineral Water 500ml — Natural Freshness Anytime",
    description:
      "Experience unmatched freshness with Pure Mineral Water. Sourced from clean and protected natural springs, this mineral water contains essential minerals that help maintain the body's balance.",
    description2:
      "Through careful filtration processes, Pure Mineral Water delivers high-quality water free from contaminants, ensuring it's safe to consume anytime.",
    benefits: ["Natural source of beneficial minerals", "Supports optimal hydration", "Clean, crisp taste", "Safe for the whole family"],
    stock: 120,
  },
  {
    id: 2,
    name: "Sparkling Water",
    price: "0.03",
    category: "Beverage",
    emoji: "🫧",
    image: "/products/sparkling-water.svg",
    company: "AquaSpark Co.",
    tagline: "Crisp carbonated refreshment with zero guilt",
    description: "Light, bubbly sparkling water crafted for everyday hydration with a satisfying fizz.",
    description2: "Perfect on its own or as a mixer — blockchain-verified supply chain from source to shelf.",
    benefits: ["Zero sugar", "Natural carbonation", "Recyclable packaging", "On-chain provenance"],
    stock: 85,
  },
  {
    id: 3,
    name: "Wireless Earbuds",
    price: "0.15",
    category: "Electronics",
    emoji: "🎧",
    image: "/products/wireless-earbuds.svg",
    company: "SoundChain Labs",
    tagline: "Studio-grade audio with Web3 ownership proof",
    description: "Premium wireless earbuds with active noise cancellation and 32-hour battery life.",
    description2: "Each unit ships with an NFT certificate of authenticity registered on Base.",
    benefits: ["ANC 2.0", "IPX5 water resistant", "Multi-device pairing", "NFT ownership proof"],
    stock: 42,
  },
  {
    id: 4,
    name: "Smart Watch",
    price: "0.40",
    category: "Electronics",
    emoji: "⌚",
    image: "/products/smart-watch.svg",
    company: "ChronoDEX",
    tagline: "Track health. Own your data.",
    description: "Advanced health monitoring with heart rate, SpO2, sleep tracking, and decentralized data vault.",
    description2: "Your biometric data stays encrypted — you control who accesses it via smart contract permissions.",
    benefits: ["7-day battery", "GPS + NFC", "Encrypted health vault", "USDC rewards for steps"],
    stock: 28,
  },
  {
    id: 5,
    name: "Cotton T-Shirt",
    price: "0.05",
    category: "Fashion",
    emoji: "👕",
    image: "/products/cotton-tshirt.svg",
    company: "ThreadDAO",
    tagline: "Organic cotton. Transparent supply chain.",
    description: "100% organic cotton tee with carbon-neutral shipping and fair-trade verified production.",
    description2: "Scan the on-chain tag to see every step from farm to your wardrobe.",
    benefits: ["Organic cotton", "Carbon-neutral ship", "Fair-trade verified", "QR provenance"],
    stock: 200,
  },
  {
    id: 6,
    name: "Denim Jacket",
    price: "0.12",
    category: "Fashion",
    emoji: "🧥",
    image: "/products/denim-jacket.svg",
    company: "Indigo Labs",
    tagline: "Timeless style meets digital ownership",
    description: "Classic denim jacket with sustainable dyeing and resale royalty built into the token.",
    description2: "Resell on Firee marketplace and earn creator royalties automatically via smart contract.",
    benefits: ["Sustainable dye", "Resale royalties", "Limited edition", "Token-gated community"],
    stock: 55,
  },
  {
    id: 7,
    name: "Granola Bar",
    price: "0.01",
    category: "Food",
    emoji: "🥜",
    image: "/products/granola-bar.svg",
    company: "NutriBlock Foods",
    tagline: "Energy-packed snack with farm-to-chain traceability",
    description: "Whole-grain granola bar with almonds, honey, and dark chocolate chips.",
    description2: "Ingredient origins verified on-chain — know exactly where your food comes from.",
    benefits: ["No artificial colors", "High protein", "Farm traceability", "Fresh batch weekly"],
    stock: 300,
  },
  {
    id: 8,
    name: "Instant Noodles",
    price: "0.01",
    category: "Food",
    emoji: "🍜",
    image: "/products/instant-noodles.svg",
    company: "NoodleNet",
    tagline: "Quick comfort food, fairly priced on-chain",
    description: "Authentic ramen-style instant noodles with rich broth seasoning sachet.",
    description2: "Peer-to-peer pricing means no middlemen — sellers set fair USDC prices directly.",
    benefits: ["3-min prep", "Rich broth", "P2P pricing", "Bulk discounts"],
    stock: 500,
  },
];

export const CATEGORIES = ["All", "Beverage", "Electronics", "Fashion", "Food"] as const;

export function getProduct(id: number): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}
