import type { Product } from "./types";

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: "ERC-20 Token Factory",
    price: "2.50",
    category: "Smart Contracts",
    emoji: "�",
    image: "/products/mineral-water.svg",
    company: "SolidityForge",
    tagline: "Deploy custom ERC-20 tokens in minutes — audited & gas-optimized",
    description:
      "Production-ready ERC-20 token contract with mint, burn, pause, and role-based access control. Fully audited and optimized for low gas deployment on Base, Ethereum, and Polygon.",
    description2:
      "Includes Hardhat test suite, deployment scripts, and Etherscan verification helper. Perfect for launching your own token project.",
    benefits: ["Audited & tested", "Gas-optimized", "Multi-chain ready", "Hardhat scripts included"],
    stock: 999,
  },
  {
    id: 2,
    name: "NFT Minting Contract",
    price: "3.00",
    category: "Smart Contracts",
    emoji: "🎨",
    image: "/products/sparkling-water.svg",
    company: "MintLab",
    tagline: "ERC-721A collection contract with allowlist & reveal",
    description: "Gas-efficient NFT minting contract using ERC-721A with built-in allowlist, delayed reveal, and royalty enforcement (EIP-2981).",
    description2: "Battle-tested on 50+ NFT launches. Includes metadata generator and IPFS upload script.",
    benefits: ["ERC-721A gas savings", "Allowlist + public mint", "Delayed reveal", "Royalty enforcement"],
    stock: 999,
  },
  {
    id: 3,
    name: "DeFi Dashboard Starter",
    price: "5.00",
    category: "DApp Templates",
    emoji: "🚀",
    image: "/products/wireless-earbuds.svg",
    company: "Web3Boilerplate",
    tagline: "Full-stack DeFi dashboard — Next.js + wagmi + RainbowKit",
    description: "Complete DeFi dashboard template with wallet connect, token balances, swap UI, and portfolio tracker.",
    description2: "Built with Next.js 14, TypeScript, Tailwind CSS, wagmi v2, and viem. Deploy to Vercel in one click.",
    benefits: ["Next.js 14 + TypeScript", "wagmi v2 + RainbowKit", "Responsive design", "One-click deploy"],
    stock: 999,
  },
  {
    id: 4,
    name: "NFT Marketplace Template",
    price: "8.00",
    category: "DApp Templates",
    emoji: "🏪",
    image: "/products/smart-watch.svg",
    company: "BuilderDAO",
    tagline: "Launch your own NFT marketplace — ready to deploy",
    description: "Full-featured NFT marketplace with listing, bidding, collection pages, and creator royalties.",
    description2: "Includes smart contracts (Solidity), frontend (React + ethers.js), and The Graph subgraph for indexing.",
    benefits: ["Listing & bidding", "Creator royalties", "Subgraph indexing", "Mobile responsive"],
    stock: 999,
  },
  {
    id: 5,
    name: "Web3 Dashboard UI Kit",
    price: "4.00",
    category: "UI Kits",
    emoji: "🎯",
    image: "/products/cotton-tshirt.svg",
    company: "CryptoUI",
    tagline: "50+ components for DeFi & Web3 dashboards",
    description: "Comprehensive UI kit with 50+ React components designed for DeFi dashboards, DEX interfaces, and Web3 apps.",
    description2: "Dark mode, responsive, accessible. Built with Tailwind CSS and Radix UI primitives.",
    benefits: ["50+ components", "Dark & light mode", "Tailwind CSS", "Radix UI primitives"],
    stock: 999,
  },
  {
    id: 6,
    name: "Wallet Connect Kit",
    price: "2.00",
    category: "UI Kits",
    emoji: "🔗",
    image: "/products/denim-jacket.svg",
    company: "ConnectLabs",
    tagline: "Beautiful wallet connection UI for any Web3 app",
    description: "Drop-in wallet connection component with support for MetaMask, WalletConnect, Coinbase, and 20+ wallets.",
    description2: "Includes network switcher, ENS resolution, balance display, and transaction history modal.",
    benefits: ["20+ wallet support", "ENS resolution", "Network switcher", "Transaction history"],
    stock: 999,
  },
  {
    id: 7,
    name: "MEV Sniper Bot",
    price: "12.00",
    category: "Tools & Scripts",
    emoji: "�",
    image: "/products/granola-bar.svg",
    company: "AlphaTools",
    tagline: "Frontrun new token listings — configurable & safe",
    description: "Automated sniper bot for Uniswap V2/V3 with configurable gas, slippage, and profit targets.",
    description2: "Runs locally on your machine. No API keys sent externally. Includes safety checks for honeypot and rug detection.",
    benefits: ["Uniswap V2 & V3", "Honeypot detection", "Configurable params", "Runs locally"],
    stock: 999,
  },
  {
    id: 8,
    name: "Airdrop Manager",
    price: "3.50",
    category: "Tools & Scripts",
    emoji: "�",
    image: "/products/instant-noodles.svg",
    company: "DropForge",
    tagline: "Bulk airdrop ERC-20 & NFTs to thousands of wallets",
    description: "Script suite to batch-send tokens or NFTs to thousands of addresses with gas optimization and retry logic.",
    description2: "Upload CSV, preview gas costs, and execute in batches. Supports ERC-20, ERC-721, and ERC-1155.",
    benefits: ["Batch sending", "Gas optimization", "CSV upload", "Multi-token support"],
    stock: 999,
  },
];

export const CATEGORIES = ["All", "Smart Contracts", "DApp Templates", "UI Kits", "Tools & Scripts"] as const;

export function getProduct(id: number): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}
